import type { CounterRule } from "../types";
import { configurationCounterRules } from "../nodeConfiguration";

/**只接收操作成功事件；累计值支持启动及配置导入后的回溯。 */
export const counterRules: CounterRule[] = [
  ...configurationCounterRules,
  ...["recognition_configured", "action_configured", "node_note", "node_json_saved", "bulk_copied"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  { counter: "terms_accepted", on: "achievement:terms_accepted" },
  { counter: "quiz_failure", on: "achievement:quiz_failure" },
  { counter: "quiz_pass", on: "achievement:quiz_pass" },
  { counter: "quiz_first", on: "achievement:quiz_first" },
  { counter: "quiz_retry", on: "achievement:quiz_retry" },
  { counter: "quiz_persistent", on: "achievement:quiz_persistent" },
  { counter: "quiz_shortcut", on: "achievement:quiz_shortcut" },

  { counter: "node_created", on: "achievement:node_created", delta: (event) => (event.payload as { count?: number } | undefined)?.count ?? 0 },
  { counter: "node_deleted", on: "achievement:node_deleted", delta: (event) => (event.payload as { count?: number } | undefined)?.count ?? 0 },
  { counter: "node_renamed", on: "achievement:node_renamed" },
  { counter: "field_added", on: "achievement:field_added" },
  { counter: "nodes_pasted", on: "achievement:nodes_pasted" },
  { counter: "edge_created", on: "achievement:edge_created", delta: (event) => (event.payload as { count?: number } | undefined)?.count ?? 0 },
  { counter: "edge_deleted", on: "achievement:edge_deleted", delta: (event) => (event.payload as { count?: number } | undefined)?.count ?? 0 },
  { counter: "edge_reordered", on: "achievement:edge_reordered" },
  ...["connection_chain", "connection_many_paths", "connection_merge", "connection_cycle", "connection_error_chain"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  { counter: "branch_created", on: "achievement:branch_created" },
  { counter: "error_edge_created", on: "achievement:error_edge_created" },
  { counter: "external_connected", on: "achievement:external_connected" },
  { counter: "layout_completed", on: "achievement:layout_completed" },
  { counter: "edge_control_moved", on: "achievement:edge_control_moved" },
  { counter: "group_organized", on: "achievement:group_organized" },
  { counter: "nodes_aligned", on: "achievement:nodes_aligned" },
  { counter: "group_color_changed", on: "achievement:group_color_changed" },
  { counter: "search_located", on: "achievement:search_located" },
  { counter: "template_saved", on: "achievement:template_saved" },
  { counter: "template_used", on: "achievement:template_used" },
  { counter: "device_connected", on: "achievement:device_connected" },
  ...["uploaded_material_used", "color_tolerance_applied", "roi_offset_measured", "delta_measured", "tool_screenshot_captured", "live_preview_collapsed"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  { counter: "screenshot_saved", on: "achievement:screenshot_saved" },
  { counter: "roi_applied", on: "achievement:roi_applied" },
  { counter: "ocr_recognized", on: "achievement:ocr_recognized" },
  { counter: "color_applied", on: "achievement:color_applied" },
  ...["debug_completed", "debug_action_completed", "debug_manual_stopped", "debug_image_opened"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  { counter: "debug_run_completed", on: "achievement:debug_run_completed" },
  { counter: "debug_single_completed", on: "achievement:debug_single_completed" },
  { counter: "debug_recognition_result", on: "achievement:debug_recognition_result" },
  { counter: "debug_details_opened", on: "achievement:debug_details_opened" },
  { counter: "debug_retry_completed", on: "achievement:debug_retry_completed" },
  { counter: "pipeline_imported", on: "achievement:pipeline_imported" },
  { counter: "pipeline_saved", on: "achievement:pipeline_saved" },
  ...["pipeline_partial_exported", "pipeline_separated_exported"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  ...["ai_edit_completed", "ai_architecture_presented", "ai_layout_applied", "ai_context_compacted"].map((counter) => ({ counter, on: `achievement:${counter}` })),
  { counter: "history_redone", on: "achievement:history_redone" },
  { counter: "debug_fix_completed", on: "achievement:debug_fix_completed" },
];
