from __future__ import annotations

PACKAGE_VERSION = "1.7.5"
PROTOCOL_VERSION = "2.0.0"
MAX_WS_MESSAGE_BYTES = 8 * 1024 * 1024
MAX_ARTIFACT_BYTES = 64 * 1024 * 1024
MAX_CONNECTION_REQUESTS = 64

RPC_METHOD_NAMES = (
    "system.hello",
    "system.health",
    "system.cancel",
    "config.get",
    "config.update",
    "config.reload",
    "workspace.scan",
    "file.open",
    "file.create",
    "file.save",
    "file.saveSeparated",
    "resource.list",
    "resource.refresh",
    "resource.image.list",
    "resource.image.get",
    "resource.image.getMany",
    "maa.device.listAdb",
    "maa.window.listDesktop",
    "maa.window.listWlroots",
    "maa.controller.create",
    "maa.controller.disconnect",
    "maa.controller.screencap",
    "maa.controller.command",
    "maa.action.execute",
    "tool.ocr",
    "tool.templateMatch",
    "tool.image.resolve",
    "tool.log.read",
    "tool.log.locate",
    "ai.complete",
    "ai.stream.start",
    "ai.stream.cancel",
    "debug.capabilities",
    "debug.session.create",
    "debug.session.destroy",
    "debug.session.snapshot",
    "debug.run.start",
    "debug.run.stop",
    "debug.events.list",
    "debug.resource.preflight",
    "debug.resource.health",
    "debug.agent.test",
    "debug.screenshot.capture",
)

EVENT_NAMES = (
    "system.error",
    "log.entry",
    "workspace.files",
    "file.content",
    "file.changed",
    "file.saved",
    "file.separatedSaved",
    "file.created",
    "config.data",
    "config.reloaded",
    "resource.bundles",
    "resource.image",
    "resource.images",
    "resource.imageList",
    "maa.adbDevices",
    "maa.desktopWindows",
    "maa.wlrootsSockets",
    "maa.controllerCreated",
    "maa.controllerStatus",
    "maa.screencap",
    "maa.commandResult",
    "maa.actionExecuted",
    "tool.ocrResult",
    "tool.templateMatchResult",
    "tool.imageResolved",
    "tool.logContent",
    "tool.logLocated",
    "ai.response",
    "ai.streamChunk",
    "debug.capabilities",
    "debug.sessionCreated",
    "debug.sessionDestroyed",
    "debug.sessionSnapshot",
    "debug.event",
    "debug.runStarted",
    "debug.runStopRequested",
    "debug.resourcePreflight",
    "debug.resourceHealth",
    "debug.agentTested",
    "debug.artifact",
)

DEFAULT_ALLOWED_ORIGINS = frozenset(
    {
        "https://mpe.codax.site",
        "https://kqcoxn.github.io",
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        "http://tauri.localhost",
        "https://tauri.localhost",
        "tauri://localhost",
    }
)
