from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, Field

from .constants import EVENT_NAMES, PROTOCOL_VERSION, RPC_METHOD_NAMES
from .models import ArtifactRef, DebugEvent, RpcEvent, RpcRequest, RpcResponse


class ProtocolDocument(BaseModel):
    message: Annotated[RpcRequest | RpcResponse | RpcEvent, Field(discriminator="type")]
    artifact: ArtifactRef
    debug_event: DebugEvent


def protocol_schema() -> dict[str, object]:
    schema = ProtocolDocument.model_json_schema()
    schema["$id"] = "https://mpe.codax.site/schema/localbridge-v2.json"
    schema["x-protocol-version"] = PROTOCOL_VERSION
    schema["x-rpc-methods"] = list(RPC_METHOD_NAMES)
    schema["x-event-names"] = list(EVENT_NAMES)
    return schema


def render_schema() -> str:
    return json.dumps(protocol_schema(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_typescript() -> str:
    rpc_methods = "\n".join(f'  | "{method}"' for method in RPC_METHOD_NAMES)
    event_names = "\n".join(f'  | "{event}"' for event in EVENT_NAMES)
    return f'''// Generated by `python -m mpe_localbridge.schema`. Do not edit.

export const BRIDGE_PROTOCOL_VERSION = "{PROTOCOL_VERSION}" as const;

export type RpcMethod =
{rpc_methods};

export type BridgeEventName =
{event_names};

export interface RpcRequest<TParams = Record<string, unknown>> {{
  v: 2;
  type: "request";
  id: string;
  method: RpcMethod;
  params: TParams;
}}

export interface RpcError {{
  code: string;
  message: string;
  data?: Record<string, unknown>;
}}

export interface RpcResponse<TResult = unknown> {{
  v: 2;
  type: "response";
  id: string;
  result?: TResult;
  error?: RpcError;
}}

export interface RpcEvent<TData = unknown> {{
  v: 2;
  type: "event";
  event: BridgeEventName;
  data: TData;
}}

export interface ArtifactRef {{
  artifactId: string;
  kind: string;
  mimeType: string;
  size: number;
  sha256: string;
  width?: number | null;
  height?: number | null;
  sessionId?: string | null;
  runId?: string | null;
  createdAt: string;
}}

export interface DebugEvent {{
  sessionId: string;
  runId?: string | null;
  seq: number;
  timestamp: string;
  source: "maafw" | "localbridge" | "mpe";
  kind: string;
  phase: string;
  status: string;
  payload: Record<string, unknown>;
  artifactRefs: ArtifactRef[];
  parentSeq?: number | null;
}}
'''


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="导出 LocalBridge v2 协议契约")
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--typescript", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    valid = _write_or_check(args.schema, render_schema(), args.check)
    valid &= _write_or_check(args.typescript, render_typescript(), args.check)
    if not valid:
        raise SystemExit("生成的协议文件存在漂移, 请重新运行 schema 导出")


if __name__ == "__main__":
    main()
