from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, Field

from .constants import EVENT_NAMES, PROTOCOL_VERSION, RPC_METHOD_NAMES
from .models import (
    ArtifactRef,
    DebugEvent,
    DocumentOpenResult,
    DocumentSaveResult,
    ProjectChangedPayload,
    ProjectDiscoveryStatus,
    ProjectEntriesPayload,
    ProjectStatus,
    ProjectStorageCapabilities,
    RpcEvent,
    RpcRequest,
    RpcResponse,
    WorkspaceDocumentsPayload,
    WorkspaceTreePayload,
)


class ProtocolDocument(BaseModel):
    message: Annotated[RpcRequest | RpcResponse | RpcEvent, Field(discriminator="type")]
    artifact: ArtifactRef
    debug_event: DebugEvent
    workspace_tree: WorkspaceTreePayload
    workspace_documents: WorkspaceDocumentsPayload
    document_open_result: DocumentOpenResult
    document_save_result: DocumentSaveResult
    project_discovery: ProjectDiscoveryStatus
    project_status: ProjectStatus
    project_capabilities: ProjectStorageCapabilities
    project_entries: ProjectEntriesPayload
    project_changed: ProjectChangedPayload


def protocol_schema() -> dict[str, object]:
    schema = ProtocolDocument.model_json_schema()
    schema["$id"] = "https://mpe.codax.site/schema/localbridge-v2.json"
    schema["x-protocol-version"] = PROTOCOL_VERSION
    schema["x-rpc-methods"] = list(RPC_METHOD_NAMES)
    schema["x-event-names"] = list(EVENT_NAMES)
    return schema


def render_schema() -> str:
    return json.dumps(protocol_schema(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_typescript() -> str:
    rpc_methods = "\n".join(f'  | "{method}"' for method in RPC_METHOD_NAMES)
    event_names = "\n".join(f'  | "{event}"' for event in EVENT_NAMES)
    return f'''// Generated by `python -m mpe_localbridge.schema`. Do not edit.

export const BRIDGE_PROTOCOL_VERSION = "{PROTOCOL_VERSION}" as const;

export type RpcMethod =
{rpc_methods};

export type BridgeEventName =
{event_names};

export interface RpcRequest<TParams = Record<string, unknown>> {{
  v: 2;
  type: "request";
  id: string;
  method: RpcMethod;
  params: TParams;
}}

export interface RpcError {{
  code: string;
  message: string;
  data?: Record<string, unknown>;
}}

export interface RpcResponse<TResult = unknown> {{
  v: 2;
  type: "response";
  id: string;
  result?: TResult;
  error?: RpcError;
}}

export interface RpcEvent<TData = unknown> {{
  v: 2;
  type: "event";
  event: BridgeEventName;
  data: TData;
}}

export interface WorkspaceTreeEntry {{
  path: string;
  name: string;
  kind: "directory" | "file";
}}

export interface WorkspaceTreePayload {{
  revision: number;
  root: string;
  entries: WorkspaceTreeEntry[];
}}

export type DocumentKind =
  | "pipeline"
  | "interface"
  | "json"
  | "text"
  | "markdown"
  | "image"
  | "binary";

export interface WorkspaceDocument {{
  path: string;
  name: string;
  kind: DocumentKind;
  language: string;
  mimeType: string;
  size: number;
  editable: boolean;
  previewable: boolean;
  readOnlyReason?: string | null;
  role?: "default_pipeline" | "mpe_config" | null;
}}

export interface WorkspaceDocumentsPayload {{
  revision: number;
  root: string;
  documents: WorkspaceDocument[];
}}

export interface ProjectCapability {{
  available: boolean;
  reason?: string | null;
}}

export interface ProjectStorageCapabilities {{
  projectId?: string | null;
  pathCaseSensitive: boolean;
  operations: Record<string, ProjectCapability>;
}}

export interface ProjectDiscoveryCandidate {{
  candidateId: string;
  interfacePath: string;
  name: string;
  label: string;
  version: string;
}}

export interface ProjectDiscoveryStatus {{
  revision: number;
  discoveryRoot: string;
  state: "discovering" | "selection_required" | "indexing" | "ready" | "invalid";
  reason: string;
  candidates: ProjectDiscoveryCandidate[];
  currentInterface?: ProjectDiscoveryCandidate | null;
  indexedFiles: number;
  totalFiles: number;
  diagnostics: Array<Record<string, unknown>>;
}}

export interface ProjectStatus {{
  revision: number;
  available: boolean;
  projectId?: string | null;
  projectRoot?: string | null;
  interfacePath?: string | null;
  name?: string | null;
  label?: string | null;
  version?: string | null;
  state: "discovering" | "selection_required" | "indexing" | "ready" | "invalid";
  indexedFiles: number;
  totalFiles: number;
}}

export interface ProjectPipelineIndex {{
  nodes: Array<Record<string, unknown>>;
  prefix: string;
  indexStatus: "pending" | "ready" | "error";
  isDefaultPipeline: boolean;
}}

export interface ProjectEntry extends Partial<WorkspaceDocument> {{
  path: string;
  name: string;
  entryKind: "directory" | "file";
  documentId?: string | null;
  pipeline?: ProjectPipelineIndex | null;
}}

export interface ProjectEntriesPayload {{
  revision: number;
  projectId?: string | null;
  entries: ProjectEntry[];
}}

export interface DocumentMapping {{
  oldPath: string;
  newPath: string;
  oldDocumentId: string;
  newDocumentId: string;
}}

export interface ProjectChangedPayload {{
  projectId: string;
  operationId: string;
  change: "created" | "modified" | "deleted" | "renamed";
  path: string;
  newPath?: string | null;
  isDirectory: boolean;
  documentMappings: DocumentMapping[];
}}

export interface DocumentOpenResult {{
  path: string;
  name: string;
  kind: DocumentKind;
  language: string;
  mimeType: string;
  size: number;
  editable: boolean;
  previewable: boolean;
  readOnlyReason?: string | null;
  role?: "default_pipeline" | "mpe_config" | null;
  content?: string;
  encoding?: "utf-8";
  revision: string;
  artifact?: ArtifactRef;
}}

export interface DocumentSaveResult {{
  path: string;
  revision: string;
  size: number;
  sha256: string;
}}

export interface ArtifactRef {{
  artifactId: string;
  kind: string;
  mimeType: string;
  size: number;
  sha256: string;
  width?: number | null;
  height?: number | null;
  sessionId?: string | null;
  runId?: string | null;
  createdAt: string;
}}

export interface DebugEvent {{
  sessionId: string;
  runId?: string | null;
  seq: number;
  timestamp: string;
  source: "maafw" | "localbridge" | "mpe";
  kind: string;
  phase: string;
  status: string;
  payload: Record<string, unknown>;
  artifactRefs: ArtifactRef[];
  parentSeq?: number | null;
}}
'''


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="导出 LocalBridge v2 协议契约")
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--typescript", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    valid = _write_or_check(args.schema, render_schema(), args.check)
    valid &= _write_or_check(args.typescript, render_typescript(), args.check)
    if not valid:
        raise SystemExit("生成的协议文件存在漂移, 请重新运行 schema 导出")


if __name__ == "__main__":
    main()
