name: Bug 反馈
description: 导入导出错误、操作异常、页面崩溃等
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      description: |
        请确认自己完成了要求之后再进行勾选
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
          required: true
        - label: 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及
          required: true
        - label: 我已使用当前预览版本的最新版复现了此问题，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
          required: true
        - label: 我填写了简短且清晰明确的标题，以便他人在翻阅 Issue 列表时能快速确定大致问题。而不是“崩溃了”等
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 描述问题时请尽可能详细
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >-
        请提供 MaaPipelineEditor 版本
      placeholder: |
        MaaPipelineEditor Version:
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: 环境信息
      description: |
        使用的浏览器、本地编译环境（若有）等
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截图或录屏
      description: |
        若文字描述不清，且能复现问题，请尽可能上传图片或视频
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        任何能让我们对你所遇到的问题有更多了解的东西，但不是另外的问题
    validations:
      required: false
