// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function GetLogsDir():Promise<string>;

export function GetPort():Promise<number>;

export function GetUpdateDownloadURL():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWorkDir():Promise<string>;

export function IsBridgeRunning():Promise<boolean>;

export function OpenLogsDir():Promise<void>;

export function OpenResourcesDir():Promise<void>;

export function OpenWorkDir():Promise<void>;

export function RestartBridge():Promise<void>;
