// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetLogsDir() {
  return window['go']['main']['App']['GetLogsDir']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetUpdateDownloadURL() {
  return window['go']['main']['App']['GetUpdateDownloadURL']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function IsBridgeRunning() {
  return window['go']['main']['App']['IsBridgeRunning']();
}

export function OpenLogsDir() {
  return window['go']['main']['App']['OpenLogsDir']();
}

export function OpenResourcesDir() {
  return window['go']['main']['App']['OpenResourcesDir']();
}

export function OpenWorkDir() {
  return window['go']['main']['App']['OpenWorkDir']();
}

export function RestartBridge() {
  return window['go']['main']['App']['RestartBridge']();
}

export function SetRootDir(arg1) {
  return window['go']['main']['App']['SetRootDir'](arg1);
}
